# Context

In this notebook we will do some exploratory data analysis to gather more information about the data and the goal of the project.  
Moreover, we will do some data cleaning and data preprocessing.

## Project context and goal:

# Load packages

In [97]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
# from scipy.stats import chi2_contingency
import warnings

warnings.filterwarnings("ignore")
pd.options.display.max_columns = 100
pd.options.display.max_rows = 100

# Load data

using relative paths

In [ ]:
filename = "data_preprocessing.ipynb"  # Current file name
print(f"Current file name: {filename}\n")
print(f"Current absolute path: {os.getcwd()}\n")

# Specify the paths, relative to the current file
ACTUAL_DIR = os.path.dirname(os.path.abspath(filename))
BASE_DIR = os.path.dirname(ACTUAL_DIR)
DATA_DIR = os.path.join(BASE_DIR, "data")
OUTPUT_DIR = os.path.join(DATA_DIR, "output_data")

print(f"BASE_DIR: {BASE_DIR}")
print(f"DATA_DIR: {DATA_DIR}")
print(f'OUTPUT_DIR: {OUTPUT_DIR}')

In [99]:
# The HISTORICO_SUERTES.xlsx should be in the data directory
df_base = pd.read_excel(os.path.join(DATA_DIR, "HISTORICO_SUERTES.xlsx"))

# First, lets modify the column names
df_base.columns = [
    x.lower()
    .strip()
    .replace(" ", "_")
    .replace(".", "_")
    .replace("-", "_")
    .replace("(", "")
    .replace(")", "")
    .replace("%", "pct_")
    for x in df_base.columns
]

df_base.head(5)

,período,hacienda,nombre,zona,tenencia,suerte,suelo,area_neta,dist_km,variedad,cod_estado_#,cod_estado,f_siembra,d_s_,ult_riego,edad_ult_cos,f_ult_corte,destino_1=semilla,cod__t_cultivo,cultivo,fec_madur_,producto,dosis_madurante,semanas_mad_,tonultcorte,tch,tchm,ton_azucar,rdto,tah,tahm,sac_caña_precosecha,edad_precosecha,pct_sac_caña,pct_sac_muestreadora,pct_atr,katrhm,pct_fibra_caña,pct_ar_jugo,pct_me_min,pct_me_veg,pct_me_tot,brix,pureza,vejez,tipo_quema,t_corte,cerca_de,cosechó,num_riegos,m3_riego,ddult_riego,lluvias_2_meses_ant_,lluvias_ciclo,lluvias_0__3,lluvias_tres_a_seis,lluvias_seis_a_nueve,luvias_9__fc,pct_infest_diatrea,fosfato_jugo,fert_nitrogen_,urea_46pct_,mez,boro_granul_,microzinc,nito_xtend,sul_amonio,nitrax_s,vinaza,codigo_estacion,temp__media_0_3,temp__media_ciclo,temp_max_ciclo,temp_min_ciclo,humedad_rel_media_0_3,humedad_rel_media_ciclo,oscilacion_temp_med_0_3,oscilacion_temp_ciclo,sum_oscilacion_temp_ciclo,radicion_solar_0_3,radiacion_solar_ciclo,precipitacion_0_3,precipitacion_ciclo,evaporacion_0_3,evaporacion_ciclo
0,201701,80493,LA CONCHA,IP02,51.0,002A,CANTARINA,6.00,4.3,CC85-92,5,Corte 5,2010-08-20,NaN,NaT,12.81,2017-01-02,0,1.0,Normal,2016-11-04,BONUS 250 EC REGULADOR FISIOLÓGICO,1.0,8.428571,727.19,121.198333,9.461228,86.050,11.8332,14.341666,1.119567,16.8172,NaN,13.7582,13.508,15.1653,1434.823641,16.910,0.84,0.355,10.198,10.553,15.7464,87.2241,2.735,VERDE,MECANIZADO,El Cerrito,AI08,NaN,0.0,0,258.0,1038.0,0.0,454.0,102.0,482.0,NaN,178.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,201701,81284,UKRANIA INCAUCA,IP05,81.0,039B,NaN,1.45,NaN,CC85-92,5,Corte 5,2011-01-27,NaN,NaT,11.14,2017-01-02,0,1.0,Normal,NaT,NaN,0.0,NaN,136.00,93.793103,8.419488,14.728,10.8294,10.157241,0.911781,NaN,NaN,12.8430,12.551,14.0410,1182.180399,16.936,0.55,2.298,7.273,9.571,15.2240,84.3602,73.823,Q.ACCIDENTAL,MANUAL,Candelaria,AI08,NaN,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,382.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,201701,80203,EL AMPARO SAA,IP05,31.0,007,CORINTIAS,8.24,23.0,CC01-1228,4,Corte 4,2011-10-25,1.65,2016-09-17,12.32,2017-01-02,0,1.0,Normal,2016-11-04,BONUS 250 EC REGULADOR FISIOLÓGICO,1.1,8.428571,1436.62,174.347087,14.151549,145.268,10.1117,17.629611,1.430974,14.7749,12.02,11.9364,11.940,13.1236,1857.192723,15.512,0.61,3.000,9.323,12.323,14.1130,84.4527,2.108,VERDE,MECANIZADO,Palmira,AI08,5.0,48513.6,107,246.0,1002.0,106.0,326.0,113.0,457.0,NaN,226.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,201701,81380,SAN JUDAS INCAUCA,IP05,82.0,013A,NaN,1.05,66.5,CC01-1940,2,Corte 2,2014-03-08,NaN,NaT,9.79,2017-01-02,0,1.0,Normal,NaT,NaN,0.0,NaN,143.63,136.790476,13.972469,13.517,9.4109,12.873333,1.314947,NaN,NaN,11.2770,10.931,12.4820,1744.043640,17.621,0.67,0.140,6.788,6.927,13.6350,82.7062,64.614,Q.ACCIDENTAL,MANUAL,Corinto,AI08,NaN,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,278.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,201701,80298,JAVA,IP06,31.0,025A,GALPON,4.53,17.0,RB73-2223,3,Corte 3,2013-01-10,1.65,NaT,11.53,2017-01-02,0,1.0,Normal,NaT,NaN,0.0,NaN,512.20,113.068432,9.806455,42.505,8.2985,9.383002,0.813790,16.7662,NaN,10.2160,10.294,11.6030,1137.843039,14.352,0.95,0.592,2.939,3.531,12.9760,78.7299,71.021,Q.ACCIDENTAL,MANUAL,Guacari,AI08,NaN,0.0,0,138.0,991.0,264.0,255.0,188.0,284.0,NaN,244.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [100]:
df_base.columns

Index(['período', 'hacienda', 'nombre', 'zona', 'tenencia', 'suerte', 'suelo',
       'area_neta', 'dist_km', 'variedad', 'cod_estado_#', 'cod_estado',
       'f_siembra', 'd_s_', 'ult_riego', 'edad_ult_cos', 'f_ult_corte',
       'destino_1=semilla', 'cod__t_cultivo', 'cultivo', 'fec_madur_',
       'producto', 'dosis_madurante', 'semanas_mad_', 'tonultcorte', 'tch',
       'tchm', 'ton_azucar', 'rdto', 'tah', 'tahm', 'sac_caña_precosecha',
       'edad_precosecha', 'pct_sac_caña', 'pct_sac_muestreadora', 'pct_atr',
       'katrhm', 'pct_fibra_caña', 'pct_ar_jugo', 'pct_me_min', 'pct_me_veg',
       'pct_me_tot', 'brix', 'pureza', 'vejez', 'tipo_quema', 't_corte',
       'cerca_de', 'cosechó', 'num_riegos', 'm3_riego', 'ddult_riego',
       'lluvias_2_meses_ant_', 'lluvias_ciclo', 'lluvias_0__3',
       'lluvias_tres_a_seis', 'lluvias_seis_a_nueve', 'luvias_9__fc',
       'pct_infest_diatrea', 'fosfato_jugo', 'fert_nitrogen_', 'urea_46pct_',
       'mez', 'boro_granul_', 'microzinc', 'nito_xtend', 'sul_amonio',
       'nitrax_s', 'vinaza', 'codigo_estacion', 'temp__media_0_3',
       'temp__media_ciclo', 'temp_max_ciclo', 'temp_min_ciclo',
       'humedad_rel_media_0_3', 'humedad_rel_media_ciclo',
       'oscilacion_temp_med_0_3', 'oscilacion_temp_ciclo',
       'sum_oscilacion_temp_ciclo', 'radicion_solar_0_3',
       'radiacion_solar_ciclo', 'precipitacion_0_3', 'precipitacion_ciclo',
       'evaporacion_0_3', 'evaporacion_ciclo'],
      dtype='object')

# Data dictionary

Although there is no official dictionary of the columns of the data set, we can make the following interpretations based on the theory and terms of the sugar sector:

In [101]:
variables_dict = {
    'período': 'Periodo de análisis o cosecha',
    'hacienda': 'codigo de la hacienda o finca donde se cultiva la caña',
    'nombre': 'Nombre de la hacienda o finca',
    'zona': 'ID Zona o ubicación del cultivo',
    'tenencia': 'Por definir',
    'suerte': 'Identificación de la unidad productiva dentro de la hacienda',
    'suelo': 'Tipo de suelo donde se cultiva la caña',
    'area_neta': 'Área neta cultivada en hectáreas',
    'dist_km': 'Distancia en kilómetros al ingenio azucarero o punto de procesamiento',
    'variedad': 'Variedad de caña de azúcar cultivada',
    'cod_estado_#': 'Código numérico del estado del cultivo',
    'cod_estado': 'Descripción del estado del cultivo',
    'f_siembra': 'Fecha de siembra del cultivo',
    'd_s_': 'Días desde la siembra hasta el análisis actual',
    'ult_riego': 'Fecha del último riego aplicado',
    'edad_ult_cos': 'Edad del cultivo en meses en la última cosecha',
    'f_ult_corte': 'Fecha del último corte del cultivo',
    'destino_1=semilla': 'Indica si la cosecha se destinó a semilla (1) o producción (0)',
    'cod__t_cultivo': 'Código del tipo de cultivo',
    'cultivo': 'Tipo de cultivo (caña de azúcar de plantación o soca)',
    'fec_madur_': 'Fecha estimada de maduración de la caña',
    'producto': 'Tipo de producto o madurante aplicado',
    'dosis_madurante': 'Dosis del madurante aplicado en la caña',
    'semanas_mad_': 'Número de semanas desde la aplicación del madurante hasta la cosecha',
    'tonultcorte': 'Toneladas de caña cosechadas en el último corte',
    'tch': 'Toneladas de caña por hectárea',
    'tchm': 'Toneladas de caña por hectárea en maduración',
    'ton_azucar': 'Toneladas de azúcar obtenidas',
    'rdto': 'Rendimiento de extracción de azúcar (%)',
    'tah': 'Toneladas de azúcar por hectárea',
    'tahm': 'Toneladas de azúcar por hectárea en maduración',
    'sac_caña_precosecha': 'Porcentaje de sacarosa en caña antes de la cosecha',
    'edad_precosecha': 'Edad del cultivo antes de la cosecha en meses',
    'pct_sac_caña': 'Porcentaje de sacarosa en caña cosechada',
    'pct_sac_muestreadora': 'Porcentaje de sacarosa determinado por muestreo',
    'pct_atr': 'Azúcar total recuperable (%)',
    'katrhm': 'Kilogramos de azúcar total recuperable por hectárea',
    'pct_fibra_caña': 'Porcentaje de fibra en la caña',
    'pct_ar_jugo': 'Porcentaje de azúcar reductora en el jugo',
    'pct_me_min': 'Porcentaje de materia extraña mineral',
    'pct_me_veg': 'Porcentaje de materia extraña vegetal',
    'pct_me_tot': 'Porcentaje total de materia extraña',
    'brix': 'Contenido de sólidos solubles en el jugo de caña (%)',
    'pureza': 'Pureza del jugo de caña (%)',
    'vejez': 'Grado de envejecimiento del cultivo',
    'tipo_quema': 'Tipo de quema antes de la cosecha (si aplica)',
    't_corte': 'Técnica de corte utilizada en la cosecha',
    'cerca_de': 'Ubicación de la parcela respecto a un punto de referencia',
    'cosechó': 'Por definir',
    'num_riegos': 'Número de riegos aplicados durante el ciclo',
    'm3_riego': 'Cantidad de agua aplicada en riego (m³)',
    'ddult_riego': 'Días desde el último riego hasta la cosecha',
    'lluvias_2_meses_ant_': 'Precipitación en los dos meses anteriores a la cosecha (mm)',
    'lluvias_ciclo': 'Precipitación acumulada en todo el ciclo de cultivo (mm)',
    'lluvias_0__3': 'Lluvias registradas en los primeros 3 meses del ciclo (mm)',
    'lluvias_tres_a_seis': 'Lluvias registradas entre los meses 3 y 6 (mm)',
    'lluvias_seis_a_nueve': 'Lluvias registradas entre los meses 6 y 9 (mm)',
    'luvias_9__fc': 'Lluvias registradas entre los meses 9 y la fecha de cosecha (mm)',
    'pct_infest_diatrea': 'Porcentaje de infestación de la plaga Diatraea',
    'fosfato_jugo': 'Por definir', #'Contenido de fosfato en el jugo de caña'
    'fert_nitrogen_': 'Cantidad de fertilizante nitrogenado aplicado',
    'urea_46pct_': 'Cantidad de urea (46% N) aplicada',
    'mez': 'Por definir',
    'boro_granul_': 'Cantidad de boro granular aplicado',
    'microzinc': 'Cantidad de zinc aplicado',
    'nito_xtend': 'Cantidad de fertilizante Nito Xtend aplicado',
    'sul_amonio': 'Cantidad de sulfato de amonio aplicado',
    'nitrax_s': 'Cantidad de Nitrax-S aplicado',
    'vinaza': 'Cantidad de vinaza aplicada al cultivo',
    'codigo_estacion': 'Por definir', #'Código de la estación meteorológica más cercana'
    'temp__media_0_3': 'Temperatura media en los primeros 3 meses del ciclo (°C)',
    'temp__media_ciclo': 'Temperatura media durante todo el ciclo (°C)',
    'temp_max_ciclo': 'Temperatura máxima registrada durante el ciclo (°C)',
    'temp_min_ciclo': 'Temperatura mínima registrada durante el ciclo (°C)',
    'humedad_rel_media_0_3_': 'Humedad relativa media en los primeros 3 meses (%)',
    'humedad_rel_media_ciclo': 'Humedad relativa media durante todo el ciclo (%)',
    'oscilacion_temp_med_0_3': 'Oscilación térmica media en los primeros 3 meses (°C)',
    'oscilacion_temp_ciclo': 'Oscilación térmica media durante el ciclo (°C)',
    'sum_oscilacion_temp_ciclo': 'Suma de la oscilación térmica durante todo el ciclo (°C)',
    'radicion_solar_0_3': 'Radiación solar en los primeros 3 meses (MJ/m²)',
    'radiacion_solar_ciclo': 'Radiación solar durante todo el ciclo (MJ/m²)',
    'precipitacion_0_3': 'Precipitación acumulada en los primeros 3 meses (mm)',
    'precipitacion_ciclo': 'Precipitación total durante el ciclo (mm)',
    'evaporacion_0_3': 'Evaporación en los primeros 3 meses (mm)',
    'evaporacion_ciclo': 'Evaporación total durante todo el ciclo (mm)',
}

# Base check & data cleaning

-->

In [102]:
df = df_base.copy()

## general

### Formats and NAN values

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21027 entries, 0 to 21026
Data columns (total 85 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   período                    21027 non-null  int64
 1   hacienda                   21027 non-null  int64
 2   nombre                     21027 non-null  object
 3   zona                       21027 non-null  object
 4   tenencia                   21026 non-null  float64
 5   suerte                     21027 non-null  object
 6   suelo                      17269 non-null  object
 7   area_neta                  21027 non-null  float64
 8   dist_km                    21022 non-null  float64
 9   variedad                   21027 non-null  object
 10  cod_estado_#               21027 non-null  int64
 11  cod_estado                 21027 non-null  object
 12  f_siembra                  21027 non-null  datetime64[ns]
 13  d_s_                       7168 non-null   object
 14  ult_riego                  8470 non-null   datetime64[ns]
 15  edad_ult_cos               21027 non-null  float64
 16  f_ult_corte                21027 non-null  datetime64[ns]
 17  destino_1=semilla          21027 non-null  int64
 18  cod__t_cultivo             21025 non-null  float64
 19  cultivo                    21025 non-null  object
 20  fec_madur_                 11252 non-null  datetime64[ns]
 21  producto                   11249 non-null  object
 22  dosis_madurante            20923 non-null  float64
 23  semanas_mad_               11252 non-null  float64
 24  tonultcorte                21027 non-null  float64
 25  tch                        21027 non-null  float64
 26  tchm                       21027 non-null  float64
 27  ton_azucar                 20786 non-null  float64
 28  rdto                       20760 non-null  float64
 29  tah                        20786 non-null  float64
 30  tahm                       20786 non-null  float64
 31  sac_caña_precosecha        19929 non-null  float64
 32  edad_precosecha            8919 non-null   float64
 33  pct_sac_caña               20578 non-null  float64
 34  pct_sac_muestreadora       19169 non-null  float64
 35  pct_atr                    20505 non-null  float64
 36  katrhm                     20505 non-null  float64
 37  pct_fibra_caña             19169 non-null  float64
 38  pct_ar_jugo                18903 non-null  float64
 39  pct_me_min                 19305 non-null  float64
 40  pct_me_veg                 19307 non-null  float64
 41  pct_me_tot                 19307 non-null  float64
 42  brix                       20760 non-null  float64
 43  pureza                     20758 non-null  float64
 44  vejez                      18582 non-null  float64
 45  tipo_quema                 21027 non-null  object
 46  t_corte                    21027 non-null  object
 47  cerca_de                   20901 non-null  object
 48  cosechó                    21027 non-null  object
 49  num_riegos                 8438 non-null   float64
 50  m3_riego                   21027 non-null  float64
 51  ddult_riego                21027 non-null  int64
 52  lluvias_2_meses_ant_       21027 non-null  float64
 53  lluvias_ciclo              21027 non-null  float64
 54  lluvias_0__3               21027 non-null  float64
 55  lluvias_tres_a_seis        21027 non-null  float64
 56  lluvias_seis_a_nueve       21027 non-null  float64
 57  luvias_9__fc               21027 non-null  float64
 58  pct_infest_diatrea         5600 non-null   float64
 59  fosfato_jugo               19169 non-null  float64
 60  fert_nitrogen_             0 non-null      float64
 61  urea_46pct_                723 non-null    float64
 62  mez                        971 non-null    float64
 63  boro_granul_               1285 non-null   float64
 64  microzinc                  1149 non-null   float64
 65  nito_xtend                 3679 non-null   float64
 66  sul_amonio                 1357 non-null   float64
 67  nitrax_s                   748 non-null    float64
 68  vinaza                     4098 non-null   float64
 69  codigo_estacion            6285 non-null   object
 70  temp__media_0_3            4530 non-null   float64
 71  temp__media_ciclo          4530 non-null   float64
 72  temp_max_ciclo             4530 non-null   float64
 73  temp_min_ciclo             4530 non-null   float64
 74  humedad_rel_media_0_3      4530 non-null   float64
 75  humedad_rel_media_ciclo    4530 non-null   float64
 76  oscilacion_temp_med_0_3    4530 non-null   float64
 77  oscilacion_temp_ciclo      4530 non-null   float64
 78  sum_oscilacion_temp_ciclo  0 non-null      float64
 79  radicion_solar_0_3         4530 non-null   float64
 80  radiacion_solar_ciclo      4530 non-null   float64
 81  precipitacion_0_3          4530 non-null   float64
 82  precipitacion_ciclo        4530 non-null   float64
 83  evaporacion_0_3            4530 non-null   float64
 84  evaporacion_ciclo          4530 non-null   float64
dtypes: datetime64[ns](4), float64(62), int64(5), object(14)
memory usage: 13.6+ MB

In [104]:
temp = pd.DataFrame(df.isna().sum().sort_values(ascending=False)).rename(columns = {0:"nan_obs"})
temp["pct_nan"] = round((temp["nan_obs"]/df.shape[0])*100,1)
temp

                           nan_obs  pct_nan
sum_oscilacion_temp_ciclo    21027    100.0
fert_nitrogen_               21027    100.0
urea_46pct_                  20304     96.6
nitrax_s                     20279     96.4
mez                          20056     95.4
microzinc                    19878     94.5
boro_granul_                 19742     93.9
sul_amonio                   19670     93.5
nito_xtend                   17348     82.5
vinaza                       16929     80.5
humedad_rel_media_ciclo      16497     78.5
temp__media_0_3              16497     78.5
oscilacion_temp_med_0_3      16497     78.5
temp__media_ciclo            16497     78.5
temp_max_ciclo               16497     78.5
humedad_rel_media_0_3        16497     78.5
radiacion_solar_ciclo        16497     78.5
evaporacion_0_3              16497     78.5
precipitacion_ciclo          16497     78.5
evaporacion_ciclo            16497     78.5
temp_min_ciclo               16497     78.5
oscilacion_temp_ciclo        16497     78.5
radicion_solar_0_3           16497     78.5
precipitacion_0_3            16497     78.5
pct_infest_diatrea           15427     73.4
codigo_estacion              14742     70.1
d_s_                         13859     65.9
num_riegos                   12589     59.9
ult_riego                    12557     59.7
edad_precosecha              12108     57.6
producto                      9778     46.5
fec_madur_                    9775     46.5
semanas_mad_                  9775     46.5
suelo                         3758     17.9
vejez                         2445     11.6
pct_ar_jugo                   2124     10.1
pct_sac_muestreadora          1858      8.8
fosfato_jugo                  1858      8.8
pct_fibra_caña                1858      8.8
pct_me_min                    1722      8.2
pct_me_veg                    1720      8.2
pct_me_tot                    1720      8.2
sac_caña_precosecha           1098      5.2
pct_atr                        522      2.5
katrhm                         522      2.5
pct_sac_caña                   449      2.1
pureza                         269      1.3
rdto                           267      1.3
brix                           267      1.3
tah                            241      1.1
ton_azucar                     241      1.1
tahm                           241      1.1
cerca_de                       126      0.6
dosis_madurante                104      0.5
dist_km                          5      0.0
cod__t_cultivo                   2      0.0
cultivo                          2      0.0
tenencia                         1      0.0
variedad                         0      0.0
edad_ult_cos                     0      0.0
area_neta                        0      0.0
suerte                           0      0.0
hacienda                         0      0.0
nombre                           0      0.0
zona                             0      0.0
período                          0      0.0
cod_estado_#                     0      0.0
cod_estado                       0      0.0
f_siembra                        0      0.0
destino_1=semilla                0      0.0
f_ult_corte                      0      0.0
lluvias_2_meses_ant_             0      0.0
cosechó                          0      0.0
tipo_quema                       0      0.0
t_corte                          0      0.0
tonultcorte                      0      0.0
tchm                             0      0.0
tch                              0      0.0
ddult_riego                      0      0.0
m3_riego                         0      0.0
lluvias_seis_a_nueve             0      0.0
luvias_9__fc                     0      0.0
lluvias_tres_a_seis              0      0.0
lluvias_0__3                     0      0.0
lluvias_ciclo                    0      0.0

**Comments**

--> We have a **total number of 85 variables**. According to the context, we can note groups of variables, for example:
- Farm and soil information
- Crop characteristics
- Crop maturity
- Before harvest
- Irrigation characteristics
- Weather conditions 
- Fertilization and supplements
- And finally, we have several metrics of crop performance (**after harvest**), i.e., TCH, sucrose percentage, among others.

--> The **columns have different formats**, some were identified as datetime type, others as integer or decimal type and others as object/categorical type variables. We will modify some columns formats in next steps.

--> As for the **presence of null values**, we noted variables with more than 80% of null observations and others with less than 10%. We can observe that groups of variables present a very similar amount of nulls, for example, the variables of crop maturity present a percentage close to 47%, variables of applied fertilizers have a percentage of more than 80% and variables of meteorological conditions present a percentage of nulls of approximately 78.5%. This should be taken into account when making decisions on the inclusion or elimination of variables.

**Cleaning actions**
1. We must keep in mind that the variables to be studied and predicted are only two: Tons of cane per hectare (TCH) and sucrose percentage of cane harvested (pct_sac_cane).  
Therefore, **all the other variables of the harvest performance metrics group should be removed**, in order to **avoid problems such as data leakage** or similar.  
Also, the variables that could be measure only after harvests, should be removed.
2. We will drop he columns with %100 of nan values (sum_oscilacion_temp_ciclo, fert_nitrogen_)

#### cleaning

In [105]:
var_to_remove = [
    "tonultcorte",
    "tchm",
    "ton_azucar",
    "rdto",
    "tah",
    "tahm",
    "sac_caña_precosecha",
    "pct_sac_muestreadora",
    "pct_atr",
    "katrhm",
    "pct_fibra_caña",
    "pct_ar_jugo",
    "pct_me_min",
    "pct_me_veg",
    "pct_me_tot",
    "brix",
    "pureza",
]

# drop columns that are metrics after harvest
df = df.drop(var_to_remove, axis=1)

# drop columns with only NAN values
df = df.drop(["sum_oscilacion_temp_ciclo", "fert_nitrogen_"], axis=1)

print(f'Number of columns: {df.shape[1]}')

Number of columns: 66

In [106]:
df.columns

Index(['período', 'hacienda', 'nombre', 'zona', 'tenencia', 'suerte', 'suelo',
       'area_neta', 'dist_km', 'variedad', 'cod_estado_#', 'cod_estado',
       'f_siembra', 'd_s_', 'ult_riego', 'edad_ult_cos', 'f_ult_corte',
       'destino_1=semilla', 'cod__t_cultivo', 'cultivo', 'fec_madur_',
       'producto', 'dosis_madurante', 'semanas_mad_', 'tch', 'edad_precosecha',
       'pct_sac_caña', 'vejez', 'tipo_quema', 't_corte', 'cerca_de', 'cosechó',
       'num_riegos', 'm3_riego', 'ddult_riego', 'lluvias_2_meses_ant_',
       'lluvias_ciclo', 'lluvias_0__3', 'lluvias_tres_a_seis',
       'lluvias_seis_a_nueve', 'luvias_9__fc', 'pct_infest_diatrea',
       'fosfato_jugo', 'urea_46pct_', 'mez', 'boro_granul_', 'microzinc',
       'nito_xtend', 'sul_amonio', 'nitrax_s', 'vinaza', 'codigo_estacion',
       'temp__media_0_3', 'temp__media_ciclo', 'temp_max_ciclo',
       'temp_min_ciclo', 'humedad_rel_media_0_3', 'humedad_rel_media_ciclo',
       'oscilacion_temp_med_0_3', 'oscilacion_temp_ciclo',
       'radicion_solar_0_3', 'radiacion_solar_ciclo', 'precipitacion_0_3',
       'precipitacion_ciclo', 'evaporacion_0_3', 'evaporacion_ciclo'],
      dtype='object')

### Identification - obs identifier

--> This exploration is **to find any possible duplicated observation**, and to find out what could be the identification of one valid observation.

In [107]:
print(f"A farm (hacienda) could have more than one harvest period:\n")
print(
    df.groupby(by="hacienda")
    .agg({"período": lambda x: x.nunique()})
    .sort_values(by="período", ascending=False)
    .rename(columns={"período": "#periodos"})
)

A farm (hacienda) could have more than one harvest period:

          #periodos
hacienda
80114            75
81363            73
80111            67
80121            67
80108            67
...             ...
81768             1
81769             1
81044             1
81046             1
81318             1

[926 rows x 1 columns]

In [108]:
print(
    f"A farm (hacienda) could have one or two different zones (zona):\ni.e. Farm id #80134 zones:\n"
)
print(df[(df["hacienda"] == 80134)].zona.value_counts())
print(f"\nGeneral:\n")
print(
    df.groupby(by="hacienda")
    .agg({"zona": lambda x: x.nunique()})
    .sort_values(by="zona", ascending=False)
    .rename(columns={"zona": "#zonas"}).iloc[5:15,:]
)

A farm (hacienda) could have one or two different zones (zona):
i.e. Farm id #80134 zones:

zona
IP05    46
IP01    17
Name: count, dtype: int64

General:

          #zonas
hacienda
80601          2
81455          2
82517          2
82524          2
80105          1
80106          1
80107          1
80108          1
80109          1
80110          1

In [109]:
print(
    f"A combination of farm-zone could have one or two different 'tenencia' values:\n"
)
df.groupby(by=["hacienda", "zona"]).agg(
    {
        "tenencia": [
            ("#", lambda x: x.nunique()),
            ("names", lambda x: x.unique().tolist()),
        ]
    }
).sort_values(by=[("tenencia", "#"), "hacienda"], ascending=[False, False]).iloc[10:20:,:]

A combination of farm-zone could have one or two different 'tenencia' values:

              tenencia
                     #         names
hacienda zona
81364    IP05        2  [81.0, 51.0]
81363    IP05        2  [81.0, 51.0]
81362    IP05        2  [81.0, 51.0]
81361    IP05        2  [81.0, 51.0]
81313    IP05        2  [81.0, 51.0]
81304    IP03        2  [81.0, 51.0]
81216    IP05        2  [82.0, 81.0]
81191    IP03        2  [81.0, 51.0]
81143    IP06        2  [81.0, 51.0]
81132    IP02        2  [81.0, 51.0]

In [110]:
print(
    f"Moreover, a combination of farm-zone-tenure could have more than one plot (suerte):\n"
)

df.groupby(by=["hacienda", "zona","tenencia"]).agg(
    {
        "suerte": [
            ("#", lambda x: x.nunique()),
            ("names", lambda x: x.unique().tolist()),
        ]
    }
)

Moreover, a combination of farm-zone-tenure could have more than one plot (suerte):

                       suerte  \
                            #
hacienda zona tenencia
80100    IP01 11.0          2
80101    IP01 11.0         78
80102    IP01 11.0        108
80103    IP01 11.0         63
80104    IP02 11.0         32
...                       ...
82550    IP06 31.0          5
82551    IP02 31.0          4
82552    IP01 11.0          6
82555    IP01 31.0          2
82557    IP06 31.0          2


                                                                    names
hacienda zona tenencia
80100    IP01 11.0                                            [001, 001A]
80101    IP01 11.0      [010Z, 012, 019C, 002B, 011, 001A, 013B, 010E,...
80102    IP01 11.0      [050A, 068E, 081C, 067C, 073C, 075B, 076A, 080...
80103    IP01 11.0      [114B, 119B, 121B, 118D, 106A, 121C, 121E, 117...
80104    IP02 11.0      [162, 152C, 164A, 165, 158, 151, 158Z, 154T, 1...
...                                                                   ...
82550    IP06 31.0                             [002, 005, 007, 007A, 012]
82551    IP02 31.0                                 [002, 003, 003A, 003B]
82552    IP01 11.0                        [041, 034, 042, 042A, 044, 043]
82555    IP01 31.0                                            [001, 001A]
82557    IP06 31.0                                             [002, 001]

[1002 rows x 2 columns]

In [111]:
print(
    f"So, taking in consideration the analysis, we could define our observations ID like the combination of period-farm-zone-tenure-plot:\n"
)
df.groupby(by=["período","hacienda", "zona","tenencia","suerte"]).count()["tch"].sort_values()

So, taking in consideration the analysis, we could define our observations ID like the combination of period-farm-zone-tenure-plot:

período  hacienda  zona  tenencia  suerte
202407   82515     IP05  11.0      001A      1
                                   001       1
         82506     IP05  11.0      001A      1
         81384     IP03  51.0      003       1
                                   001       1
                                            ..
201701   80123     IP06  11.0      542A      1
         80121     IP01  11.0      047D      1
                                   047A      1
202407   82552     IP01  11.0      043       1
201701   80108     IP06  11.0      324A      1
Name: tch, Length: 21026, dtype: int64

In [112]:
df.shape

(21027, 66)

In [113]:
print(
    f"And also, we could determine the harvests carried out in the same plot or same soil, with the combination of the variables farm-zone-tenure-plot \n"
)
df.groupby(by=["hacienda", "zona","tenencia","suerte"]).count()["tch"].sort_values()

And also, we could determine the harvests carried out in the same plot or same soil, with the combination of the variables farm-zone-tenure-plot

hacienda  zona  tenencia  suerte
82551     IP02  31.0      003B      1
80101     IP01  11.0      010K      1
                          010U      1
                          010Y      1
80668     IP03  51.0      001B      1
                                   ..
80526     IP05  51.0      007       8
80605     IP01  91.0      002       8
80203     IP05  31.0      007       8
81146     IP05  51.0      016       9
80156     IP06  31.0      003       9
Name: tch, Length: 6384, dtype: int64

**Comments**

--> An observation ID is the combination of 5 variables: "período-hacienda-zona-tenencia-suerte".  
We found no duplicate observations, because the grouping and counting of the 5 variables match the number of rows in the df.

**Cleaning actions**
1. No cleaning steps are necessary, since there are no duplicate observations.

## Identification and farm variables

In [114]:
group_variables = ["hacienda","nombre","zona","tenencia","suerte","suelo","area_neta", "dist_km"]
print(df[group_variables].info())
print("----")
print(f'\nNumer of NAN values:\n\n{df[group_variables].isna().sum()}')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21027 entries, 0 to 21026
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   hacienda   21027 non-null  int64
 1   nombre     21027 non-null  object
 2   zona       21027 non-null  object
 3   tenencia   21026 non-null  float64
 4   suerte     21027 non-null  object
 5   suelo      17269 non-null  object
 6   area_neta  21027 non-null  float64
 7   dist_km    21022 non-null  float64
dtypes: float64(3), int64(1), object(4)
memory usage: 1.3+ MB
None
----

Numer of NAN values:

hacienda        0
nombre          0
zona            0
tenencia        1
suerte          0
suelo        3758
area_neta       0
dist_km         5
dtype: int64

Nombre

In [115]:
df.nombre.value_counts()

nombre
MARSELLA                      404
ESPERANZA  INESA              330
PETITE SAN FELIPE             272
SAN FERNANDO                  262
PIEDECHINCHE                  249
                             ...
ABROJAL MANUELITA               1
UKRANIA SDOVNIK  P INCAUCA      1
HATO SANTA LUCIA                1
URUBAMBA MANUELITA              1
ORIENTE MANUELITA               1
Name: count, Length: 914, dtype: int64

In [116]:
print(
    f"Some farms (hacienda) have more than one name. This could be due to typos:\ni.e. Farm id #80677 names:\n"
)
print(df[(df["hacienda"] == 80677)].nombre.value_counts())
print(f"\nGeneral:\n")
print(
    df.groupby(by="hacienda")
    .agg({"nombre": lambda x: x.nunique()})
    .sort_values(by="nombre", ascending=False)
)

Some farms (hacienda) have more than one name. This could be due to typos:
i.e. Farm id #80677 names:

nombre
SINCERIN #4 GRACIELA    4
SINCERIN #4A1           2
Name: count, dtype: int64

General:

          nombre
hacienda
80394          2
80677          2
80360          2
80518          2
80316          2
...          ...
82550          1
82551          1
82552          1
82555          1
80101          1

[926 rows x 1 columns]

zona

In [117]:
df.zona.value_counts()

zona
IP05    7813
IP03    5184
IP06    4113
IP01    2307
IP02    1595
ip05      14
IC07       1
Name: count, dtype: int64

tenencia

In [118]:
df.tenencia.value_counts()

tenencia
51.0    9968
31.0    3916
81.0    3528
11.0    3089
28.0     326
91.0     186
82.0      13
Name: count, dtype: int64

suerte

In [119]:
df.suerte.value_counts()

suerte
001     2188
002     1535
003     1249
004      979
005      812
        ...
045B       1
126C       1
009E       1
085C       1
504        1
Name: count, Length: 1220, dtype: int64

In [120]:
print(f'Number of levels of "suerte": {df.suerte.nunique()}')

Number of levels of "suerte": 1220

suelo

In [121]:
df.suelo.value_counts()

suelo
CORINTIAS             4042
GALPON                2282
PALMIRA               1457
MANUELITA              742
NUEVO PICHICHI         599
                      ...
PUERTO TEJADA            2
BRITANIA-CHUNDULAR       2
JORDAN-NIMA              2
UNION                    1
Sinaí                    1
Name: count, Length: 102, dtype: int64

In [122]:
print(f'Number of levels of "suelo": {df.suelo.nunique()}')

Number of levels of "suelo": 102

area_neta

In [123]:
df.area_neta.value_counts()

area_neta
1.000     157
4.000     121
2.000     116
3.000     108
5.000      93
         ...
8.053       1
21.240      1
14.800      1
26.430      1
2.798       1
Name: count, Length: 2397, dtype: int64

**Comments**

-->

**Cleaning actions**
1. We will drop the "nombre" column, because this variable do not give valuable information and have some typos.
2. We will modify the "zona" levels, lowering the letters.
3. All variables belonging to the observation identifier, will be cast to object format.
4. We will modify the "suelo" levels, lowering the letters and replacing the spaces with underscore.
5. We will sort the dataframe according to the identifier of obs.

In [124]:
# drop column "nombre"
df = df.drop("nombre",axis=1)

# lower the levels of variable "zona"
df.zona = df.zona.str.lower()

# Cast hacienda & tenencia to object format
df[["hacienda","tenencia"]] = df[["hacienda","tenencia"]].astype(object)

# modify the levels of "suelo"
df.suelo = df.suelo.str.strip().str.lower().str.replace(" ","_")

# sort the dataframe
df = df.sort_values(by=["período","hacienda","zona","suerte","f_siembra"], ascending=[True,True,True,True,True]).reset_index(drop=True)

# list of pre-processing steps

1.
2.
3.
4.
5.
6.

# Export data

In [130]:
# # Export df to output DIR --- AWARE-ONLY WHEN NEEDED
# OUTPUT_FILE = os.path.join(OUTPUT_DIR, "suertes_clean.csv")
# df.to_csv(OUTPUT_FILE)

# resources and bibliography