# Context

In this notebook we will

# Load packages

In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

# from scipy.stats import chi2_contingency
import warnings

warnings.filterwarnings("ignore")
pd.options.display.max_columns = 100
pd.options.display.max_rows = 100

# Load data

using relative paths

In [45]:
filename = "FE_regression.ipynb"  # Current file name
print(f"Current file name: {filename}\n")
print(f"Current absolute path: {os.getcwd()}\n")

# Specify the paths, relative to the current file
ACTUAL_DIR = os.path.dirname(os.path.abspath(filename))
BASE_DIR = os.path.dirname(ACTUAL_DIR)
DATA_DIR = os.path.join(BASE_DIR, "data")
OUTPUT_DIR = os.path.join(DATA_DIR, "output_data")

print(f"BASE_DIR: {BASE_DIR}")
print(f"DATA_DIR: {DATA_DIR}")
print(f"OUTPUT_DIR: {OUTPUT_DIR}")

Current file name: FE_regression.ipynb

Current absolute path: c:\Users\jhona\Dropbox\ASPECTOS MAESTRIA\Cursos semestres\SEMESTRE 1\Aprendizaje automatico 1\PROYECTO FINAL\ML1_industria_azucarera\notebooks

BASE_DIR: c:\Users\jhona\Dropbox\ASPECTOS MAESTRIA\Cursos semestres\SEMESTRE 1\Aprendizaje automatico 1\PROYECTO FINAL\ML1_industria_azucarera
DATA_DIR: c:\Users\jhona\Dropbox\ASPECTOS MAESTRIA\Cursos semestres\SEMESTRE 1\Aprendizaje automatico 1\PROYECTO FINAL\ML1_industria_azucarera\data
OUTPUT_DIR: c:\Users\jhona\Dropbox\ASPECTOS MAESTRIA\Cursos semestres\SEMESTRE 1\Aprendizaje automatico 1\PROYECTO FINAL\ML1_industria_azucarera\data\output_data

In [46]:
df = pd.read_csv(os.path.join(OUTPUT_DIR, "suertes_clean.csv")).iloc[:, 1:]

df.head(5)

,tch,pct_sac_caña,periodo,hacienda,zona,suerte,suelo,area_neta,dist_km,cerca_de,variedad,cult_organico,num_cosechas,f_siembra,f_ult_corte,edad_ult_cos,edad_precosecha,vejez,pct_infest_diatrea,fec_madur_,producto,dosis_madurante,semanas_mad_,ult_riego,ddult_riego,num_riegos,m3_riego,lluvias_2_meses_ant_,lluvias_0__3,lluvias_tres_a_seis,lluvias_seis_a_nueve,lluvias_9_a_cos,lluvias_ciclo,tipo_quema,t_corte,codigo_estacion,temp__media_0_3,temp__media_ciclo,temp_max_ciclo,temp_min_ciclo,humedad_rel_media_0_3,humedad_rel_media_ciclo,oscilacion_temp_med_0_3,oscilacion_temp_ciclo,radicion_solar_0_3,radiacion_solar_ciclo,precipitacion_0_3,precipitacion_ciclo,evaporacion_0_3,evaporacion_ciclo,vinaza,fosfato_jugo,urea_46pct_,mez,boro_granul_,microzinc,nito_xtend,sul_amonio,nitrax_s
0,149.714285,9.9300,201701,80108,ip06,324A,manuelita,1.26,7.5,el_cerrito,cc01_1940,0.0,1,2015-04-01,2017-01-20,12.68,11.27,NaN,NaN,NaN,no_especificado,NaN,NaN,2016-08-25,148.0,1.0,2588.40,192.0,110.0,369.0,103.0,403.0,985.0,verde,manual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13860.0,298.0000,200.0,50.0,NaN,NaN,NaN,NaN,NaN
1,129.673316,10.7856,201701,80108,ip06,326,manuelita,4.01,7.5,el_cerrito,cc85_92,0.0,8,2007-07-09,2017-01-21,12.02,10.58,15.540,NaN,NaN,no_especificado,NaN,NaN,2016-10-10,103.0,3.0,19960.50,192.0,190.0,309.0,168.0,314.0,981.0,q_programada,manual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36090.0,174.6750,600.0,200.0,80.0,80.0,NaN,NaN,NaN
2,139.855072,11.5614,201701,80108,ip06,328A,manuelita,2.07,7.5,el_cerrito,cc04_667,0.0,1,2015-02-18,2017-01-28,12.48,10.81,1.930,NaN,2016-12-13,bonus_250_ec_regulador_fisiologico,1.0,6.571428,2016-09-17,133.0,2.0,4933.08,172.0,180.0,307.0,149.0,345.0,981.0,verde,mecanizado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,294.1528,200.0,100.0,NaN,NaN,NaN,NaN,NaN
3,157.754901,10.9520,201701,80108,ip06,331B,genova,3.06,7.5,el_cerrito,rb73_2223,0.0,3,2013-07-31,2017-01-20,12.09,10.68,10.312,NaN,2016-12-13,bonus_250_ec_regulador_fisiologico,1.0,5.428571,2016-09-28,114.0,4.0,33390.86,298.0,348.0,345.0,182.0,476.0,1351.0,verde,manual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36720.0,286.0000,450.0,150.0,NaN,NaN,NaN,NaN,NaN
4,127.289256,9.3950,201701,80108,ip06,332B,genova,1.21,7.5,el_cerrito,cc97_7170,0.0,1,2015-02-01,2017-01-20,12.12,10.71,NaN,NaN,NaN,no_especificado,NaN,NaN,NaN,NaN,NaN,NaN,149.0,280.0,308.0,152.0,298.0,1038.0,verde,manual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,257.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Create new variables

In [47]:
df.columns

Index(['tch', 'pct_sac_caña', 'periodo', 'hacienda', 'zona', 'suerte', 'suelo',
       'area_neta', 'dist_km', 'cerca_de', 'variedad', 'cult_organico',
       'num_cosechas', 'f_siembra', 'f_ult_corte', 'edad_ult_cos',
       'edad_precosecha', 'vejez', 'pct_infest_diatrea', 'fec_madur_',
       'producto', 'dosis_madurante', 'semanas_mad_', 'ult_riego',
       'ddult_riego', 'num_riegos', 'm3_riego', 'lluvias_2_meses_ant_',
       'lluvias_0__3', 'lluvias_tres_a_seis', 'lluvias_seis_a_nueve',
       'lluvias_9_a_cos', 'lluvias_ciclo', 'tipo_quema', 't_corte',
       'codigo_estacion', 'temp__media_0_3', 'temp__media_ciclo',
       'temp_max_ciclo', 'temp_min_ciclo', 'humedad_rel_media_0_3',
       'humedad_rel_media_ciclo', 'oscilacion_temp_med_0_3',
       'oscilacion_temp_ciclo', 'radicion_solar_0_3', 'radiacion_solar_ciclo',
       'precipitacion_0_3', 'precipitacion_ciclo', 'evaporacion_0_3',
       'evaporacion_ciclo', 'vinaza', 'fosfato_jugo', 'urea_46pct_', 'mez',
       'boro_granul_', 'microzinc', 'nito_xtend', 'sul_amonio', 'nitrax_s'],
      dtype='object')

In [70]:
df.groupby("hacienda").agg(
    {"suelo": lambda x: x.nunique(), "variedad": lambda x: x.shape[0]}
).sort_values(by="suelo", ascending=False)

          suelo  variedad
hacienda
80102        13       196
80111         9       204
80101         8       134
80113         7        49
80105         7        56
...         ...       ...
81268         0         6
81265         0         1
81259         0         2
81258         0         1
81256         0         3

[920 rows x 2 columns]

In [73]:
df.columns

Index(['tch', 'pct_sac_caña', 'periodo', 'hacienda', 'zona', 'suerte', 'suelo',
       'area_neta', 'dist_km', 'cerca_de', 'variedad', 'cult_organico',
       'num_cosechas', 'f_siembra', 'f_ult_corte', 'edad_ult_cos',
       'edad_precosecha', 'vejez', 'pct_infest_diatrea', 'fec_madur_',
       'producto', 'dosis_madurante', 'semanas_mad_', 'ult_riego',
       'ddult_riego', 'num_riegos', 'm3_riego', 'lluvias_2_meses_ant_',
       'lluvias_0__3', 'lluvias_tres_a_seis', 'lluvias_seis_a_nueve',
       'lluvias_9_a_cos', 'lluvias_ciclo', 'tipo_quema', 't_corte',
       'codigo_estacion', 'temp__media_0_3', 'temp__media_ciclo',
       'temp_max_ciclo', 'temp_min_ciclo', 'humedad_rel_media_0_3',
       'humedad_rel_media_ciclo', 'oscilacion_temp_med_0_3',
       'oscilacion_temp_ciclo', 'radicion_solar_0_3', 'radiacion_solar_ciclo',
       'precipitacion_0_3', 'precipitacion_ciclo', 'evaporacion_0_3',
       'evaporacion_ciclo', 'vinaza', 'fosfato_jugo', 'urea_46pct_', 'mez',
       'boro_granul_', 'microzinc', 'nito_xtend', 'sul_amonio', 'nitrax_s',
       'edad_siembra_a_ult_cos', 'variedad_v2', 'producto_categoria',
       'riego_l_ha', 'agua_total_l_ha', 'vinaza_p_ha'],
      dtype='object')

## Total crop-soil age in months

Months beetwen the sowing and the current harvest

The formula used, take into account 365.25 days per year, and 12 month per year.  
 Two days are substracted from the total days, to align with the "edad_ult_cos" column formula.

In [48]:
# Firts, cast the columns to datetime colums
df.f_siembra = pd.to_datetime(df.f_siembra)
df.f_ult_corte = pd.to_datetime(df.f_ult_corte)

# Create the total soil-crop age, by substracting the harvest date and the sowing date, then convert to months
total_days = (df.f_ult_corte - df.f_siembra).dt.days
df["edad_siembra_a_ult_cos"] = (total_days - 2) / (365.25 / 12)

In [49]:
df.edad_siembra_a_ult_cos.describe()

count    20698.000000
mean        67.937188
std         51.705853
min          6.735113
25%         31.145791
50%         54.275154
75%         87.260780
max        410.119097
Name: edad_siembra_a_ult_cos, dtype: float64

## Macro variety of crops
Take into account the variety of the sugar cane, and develop a new macro-variety column.

More info related:

- Colombian varieties (CC - CENICAÑA).
- The first two digits from Colombian varieties, are the year of release.  
- RB varieties (Brazilian varieties), PR varieties (Puerto Rican varieties), SP varieties (São Paulo, Brazil), Q varieties (Queensland, Australia), Other origins (CO, V, MZC, etc.)

ref:
- https://www.cenicana.org/pdf_privado/serie_tecnica/st_31/st_31.pdf
- https://tecnicana.org/2024/04/25/asociaciones-centros-investigacion/un-universo-de-variedades-la-cana-de-azucar-en-colombia/?v=42983b05e2f2

In [50]:
df.variedad.unique()

array(['cc01_1940', 'cc85_92', 'cc04_667', 'rb73_2223', 'cc97_7170',
       'cc92_2804', 'sp71_6949', 'cc00_3257', 'cc93_4418', 'pr61_632',
       'v71_51', 'cc84_75', 'cc01_1228', 'cc93_4181', 'cc98_72',
       'cc01_385', 'cc00_3771', 'pr1248', 'pr1141', 'varias', 'cc03_469',
       'cc91_1606', 'co421', 'rd75_11', 'cc01_746', 'cc01_678',
       'cc00_3885', 'cc93_3895', 'cc82_15', 'cc92_2198', 'cc09_235',
       'cc04_195', 'cc09_702', 'cc09_066', 'q208', 'rb85_5113',
       'cc00_3079', 'cc05_430', 'cc11_600', 'cc06_783', 'q191',
       'cc03_1029', 'cc06_791', 'cc09_535', 'cc11_595', 'cc99_2461',
       'cc10_450', 'cc01_1236', 'cc11_605', 'cc05_230', 'cc12_2120',
       'cc09_449', 'cc05_231', 'cc15_2356', 'cc15_2495', 'mzc74_275',
       'cc11_2132'], dtype=object)

In [51]:
temp = sum(["cc" not in x for x in df.variedad.unique()])
temp_cc = sum(["cc" in x for x in df.variedad.unique()])

print(
    f"The dataset have {temp_cc} Colombian varieties and {temp} varieties from other countries."
)

The dataset have 44 Colombian varieties and 13 varieties from other countries.

We will group the varieties according to:

1. cc varieties from 80's
2. cc varieties from 90's
3. cc varieties equal or greather than 2000's
4. Varieties from other countries.

In [52]:
df["variedad_v2"] = np.where(
    (df.variedad.str.contains("cc8")) | (df.variedad.str.contains("cc9")),
    "cc_menor_2000",
    np.where(
        (df.variedad.str.contains("cc0")) | (df.variedad.str.contains("cc1")),
        "cc_mayor_2000",
        "others",
    ),
)

In [53]:
df.groupby(by="variedad_v2").agg({"tch": "mean", "f_siembra": "count"}).sort_values(
    by="tch", ascending=False
)

                      tch  f_siembra
variedad_v2
cc_mayor_2000  136.067574      12863
others         120.506867       1611
cc_menor_2000  120.143240       6224

## Type of product added to the crop

Macro categories for the column "producto"

In [54]:
df.producto.unique()

array(['no_especificado', 'bonus_250_ec_regulador_fisiologico',
       'agrofosk_m', 'fusilade_2000_bl', 'otros_madurantes',
       'producto_ensayo_en_litros', 'round_up_monsanto_747_granulado',
       'fertilizante_liquido_rendimiento', 'green_life',
       'madurante_regulador_tronnuspac_250_ec', 'coadyuvante__douce',
       'madurante_bio_safe_organic', 'amina_2_4_d', 'baykal',
       'herbicida_click_40_sc', 'glifolaq', 'translok',
       'fertilizante_orgánico_pater_m'], dtype=object)

In [55]:
def categorize_producto(producto):
    # Ripeners/Maturation Agents (Madurantes)
    if any(
        term in producto for term in ["madurante", "bonus_250_ec_regulador_fisiologico"]
    ):
        return "Madurante"

    # Herbicides
    elif any(
        term in producto
        for term in [
            "fusilade",
            "round_up",
            "amina_2_4_d",
            "herbicida",
            "glifolaq",
            "translok",
        ]
    ):
        return "Herbicida"

    # Fertilizers and biostimulants
    elif any(
        term in producto
        for term in ["fertilizante", "agrofosk", "green_life", "baykal"]
    ):
        return "Fertilizante/bioestimulante"

    # Adjuvants
    elif any(term in producto for term in ["coadyuvante"]):
        return "Coadyuvante"

    # Experimental/Other
    elif "producto_ensayo" in producto:
        return "Experimental"

    # Not specified
    else:
        return "No especificado"


# Apply the function to create the new column
df["producto_categoria"] = df["producto"].apply(categorize_producto)

In [56]:
df["producto_categoria"].value_counts()

producto_categoria
Madurante                      10404
No especificado                 9483
Coadyuvante                      380
Fertilizante/bioestimulante      289
Herbicida                        124
Experimental                      18
Name: count, dtype: int64

## Liters of irrigation per hectare (L/ha)

"m3_riego" per hectares of the soil

In [57]:
# First convert m³ to liters (1 m³ = 1000 L)
# Then divide by hectares to get liters per hectare

df["riego_l_ha"] = (df.m3_riego / df.area_neta) * 1000

In [58]:
df["riego_l_ha"].describe()

count    8.201000e+03
mean     1.060781e+07
std      7.996226e+07
min      8.590519e+03
25%      3.237761e+06
50%      6.459701e+06
75%      1.004972e+07
max      5.020200e+09
Name: riego_l_ha, dtype: float64

## Total liters of water per hectare
we add the total mm of rainfall to the cubic meters of water and divided by the hectares of the crop.

In [ ]:
# Convert rainfall (mm) to liters per hectare
# 1 mm = 1 L/m2
# 1 mm over 1 hectare = 10,000 liters

df["lluvias_l"] = df["lluvias_ciclo"] * 10000

# Sum the columns, even if one of the columns is missing a value
df["agua_total_l_ha"] = df[["lluvias_l", "riego_l_ha"]].sum(axis=1, min_count=1)

df.drop("lluvias_l", axis=1, inplace=True)

In [60]:
df.agua_total_l_ha.describe()

count    1.320700e+04
mean     1.479351e+07
std      6.350678e+07
min      2.000000e+04
25%      5.753000e+06
50%      1.303439e+07
75%      1.811382e+07
max      5.031030e+09
Name: agua_total_l_ha, dtype: float64

## Vinaza per hectare

in vinaza units (is unknown) per hectare but likely to be liters/ha

In [61]:
# Vinaza divided by the hectares of the soil
df["vinaza_p_ha"] = df.vinaza / df.area_neta

# avoid the outliers
df["vinaza_p_ha"] = np.where(
    df["vinaza_p_ha"] < df["vinaza_p_ha"].quantile(0.005), np.nan, df["vinaza_p_ha"]
)
df["vinaza_p_ha"] = np.where(
    df["vinaza_p_ha"] > df["vinaza_p_ha"].quantile(0.995), np.nan, df["vinaza_p_ha"]
)

## Info about previous harvests in the same soil

# Avoid outliers

We will to drop the 0.003% of values with higher and lower values in some column, in order to avoid any potential outlier or error.

In [62]:
df.shape

(20698, 65)

In [64]:
columns_to_clean = [
    "num_cosechas",
    "edad_ult_cos",
    "edad_siembra_a_ult_cos",
    "semanas_mad_",
    "riego_l_ha",
    "agua_total_l_ha",
]

for column in columns_to_clean:
    df = df[
        (
            (df[column] <= df[column].quantile(0.997))
            & (df[column] >= df[column].quantile(0.003))
        )
        | (df[column].isnull())
    ]

In [65]:
df.shape

(20214, 65)